version: '3.5'
services:

  web-server:
    image: nginx:latest
    container_name: web-server
    restart: always
    volumes:
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - demo-mysql-gorm
      - mysql-demo
    ports:
      - 80:80

  mysql-demo :
    image: mysql:latest
    container_name: mysql-demo
    restart: always
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=#demo#MySQL
      - MYSQL_DATABASE=demoMySQL
    ports:
      - 3306:3306

  demo-mysql-gorm:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: demo-mysql-gorm
    restart: always
    depends_on:
      - mysql-demo
    ports:
      - 3000:3000

volumes:
  my-datavolume:



# docker run --name=mysql_demo -e MYSQL_ROOT_PASSWORD=#demo#MySQL -e MYSQL_DATABASE=demoMySQL -p 3306:3306 -d mysql
# CREATE TABLE Persons (
#     PersonID int,
#     LastName varchar(255),
#     FirstName varchar(255),
#     Address varchar(255),
#     City varchar(255)
# );

# CREATE TABLE `Address` (
#     `addrID`       int(11)     NOT NULL   auto_increment,
#     `addrStreet`   varchar(50) NOT NULL   default '',
#     `addrCity`     varchar(25) NOT NULL   default '',
#     `addrSoy`    char(2)     NOT NULL   default '',
#     `addrZIP`      char(10)    NOT NULL   default '',
#     PRIMARY KEY (`addrID`)
# );